name: Build Project and Test 

on:
  pull_request:
    branches: ['main']

  # Run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build in order to ensure the project compiles on a pull request
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm test