name: Deploy

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4.0.0

            - name: Setup Node
              uses: actions/setup-node@v3.8.1
              with:
                  node-version: 19.9

            - name: Install dependencies
              uses: bahmutov/npm-install@v1.6.0

            - name: Build project
              run: npm run build

            - name: Upload production-ready build files
              uses: actions/upload-artifact@v3.1.3
              with:
                  name: production-files
                  path: ./dist

    deploy:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'

        steps:
            - name: Download artifact
              uses: actions/download-artifact@v2.1.1
              with:
                  name: production-files
                  path: ./dist

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4.4.3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  folder: ./dis
